[package]
name = "scop"
version = "0.1.0"
edition = "2021"

[profile.dev]
jobs = 4
incremental = true
opt-level = 3

[profile.release]
strip = "symbols"

[dependencies]
glium = "0.31.0"
image = "0.24.2"